version: '3.8'

services:
  broker_firm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  h2:
    image: oscarfonts/h2
    restart: always
    ports:
      - "8082:8082"
