spring:
  application.name: broker_firm
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      sql: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
